---
s1:
  program: simple
  rules:
    - table: MyIngress.ipv4_lpm
      match: 10.0.1.1/24 #h1
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:01:00 #h1
        - 1
    - table: MyIngress.ipv4_lpm
      match: 10.0.2.1/24 #h2
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:02:00 #h2
        - 2
s2:
  program: simple
  rules:
    - table: MyIngress.ipv4_lpm
      match: 10.0.1.1/24 #h1
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:01:00 #h1
        - 1
    - table: MyIngress.ipv4_lpm
      match: 10.0.2.1/24 #h2
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:02:00 #h2
        - 2
s3:
  program: simple1
  rules:
    - table: MyIngress.ipv4_lpm1
      match: 10.0.1.1/24 #h1
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:01:00 #h1
        - 1
    - table: MyIngress.ipv4_lpm1
      match: 10.0.2.1/24 #h2
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:02:00 #h2
        - 2
s4:
  program: simple1
  rules:
    - table: MyIngress.ipv4_lpm1
      match: 10.0.1.1/24 #h1
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:01:00 #h1
        - 2
    - table: MyIngress.ipv4_lpm1
      match: 10.0.2.1/24 #h2
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:02:00 #h2
        - 1
