---
s1:
  program: asymmetric
  digest:
    - digest_t
  rules:
    - table: MyIngress.ipv4_lpm
      match: 10.0.1.1/24 #h1
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:01:00
        - 1
    - table: MyIngress.ipv4_lpm
      match: 10.0.2.1/24 #h2
      action: MyIngress.ipv4_forward
      action_param:
        - 08:00:00:00:02:00
        - 2
